import { Question } from './types';

export const QUESTIONS: Question[] = [
  // Level 1: Basic
  { id: 1, text: "¿Quién ganó el Mundial de 2022?", options: ["Francia", "Argentina", "Brasil", "Croacia"], correctAnswer: "Argentina", difficulty: 1 },
  { id: 2, text: "¿Cuántos jugadores hay en un equipo de fútbol en el campo?", options: ["10", "11", "12", "9"], correctAnswer: "11", difficulty: 1 },
  { id: 3, text: "¿En qué país se inventó el fútbol moderno?", options: ["Brasil", "Inglaterra", "España", "Italia"], correctAnswer: "Inglaterra", difficulty: 1 },
  { id: 4, text: "¿Cómo se llama el estadio del Real Madrid?", options: ["Camp Nou", "Santiago Bernabéu", "Metropolitano", "Mestalla"], correctAnswer: "Santiago Bernabéu", difficulty: 1 },
  { id: 5, text: "¿Quién es conocido como 'O Rei'?", options: ["Maradona", "Pelé", "Messi", "Cristiano Ronaldo"], correctAnswer: "Pelé", difficulty: 1 },
  { id: 6, text: "¿Cada cuántos años se juega el Mundial?", options: ["2", "3", "4", "5"], correctAnswer: "4", difficulty: 1 },
  { id: 7, text: "¿Qué parte del cuerpo no puede tocar el balón un jugador de campo?", options: ["Cabeza", "Pecho", "Manos", "Pies"], correctAnswer: "Manos", difficulty: 1 },
  { id: 8, text: "¿Cuál es el color de la tarjeta que expulsa a un jugador?", options: ["Amarilla", "Azul", "Roja", "Verde"], correctAnswer: "Roja", difficulty: 1 },
  { id: 9, text: "¿Quién ganó el Balón de Oro 2023?", options: ["Haaland", "Mbappé", "Messi", "Bellingham"], correctAnswer: "Messi", difficulty: 1 },
  { id: 10, text: "¿En qué ciudad juega el FC Barcelona?", options: ["Madrid", "Barcelona", "Sevilla", "Valencia"], correctAnswer: "Barcelona", difficulty: 1 },
  { id: 11, text: "¿Cómo se llama el máximo goleador histórico de los mundiales?", options: ["Ronaldo Nazário", "Miroslav Klose", "Pelé", "Messi"], correctAnswer: "Miroslav Klose", difficulty: 1 },
  { id: 12, text: "¿Qué equipo tiene más Champions League?", options: ["AC Milan", "Liverpool", "Real Madrid", "Bayern Múnich"], correctAnswer: "Real Madrid", difficulty: 1 },
  { id: 13, text: "¿A qué selección le dicen 'La Roja'?", options: ["Chile", "España", "Ambas", "Ninguna"], correctAnswer: "Ambas", difficulty: 1 },
  { id: 14, text: "¿Quién es el 'Bicho'?", options: ["Messi", "Neymar", "Cristiano Ronaldo", "Suárez"], correctAnswer: "Cristiano Ronaldo", difficulty: 1 },
  { id: 15, text: "¿En qué equipo debutó Lionel Messi?", options: ["PSG", "Newell's Old Boys", "FC Barcelona", "Inter Miami"], correctAnswer: "FC Barcelona", difficulty: 1 },
  { id: 16, text: "¿Cuál es el máximo de cambios permitidos en un partido oficial actualmente?", options: ["3", "4", "5", "6"], correctAnswer: "5", difficulty: 1 },
  { id: 17, text: "¿Qué selección ganó el Mundial de Sudáfrica 2010?", options: ["Holanda", "España", "Alemania", "Uruguay"], correctAnswer: "España", difficulty: 1 },
  { id: 18, text: "¿Cómo se llama la liga de fútbol de España?", options: ["Premier League", "Serie A", "LaLiga", "Bundesliga"], correctAnswer: "LaLiga", difficulty: 1 },
  { id: 19, text: "¿Qué equipo juega en Anfield?", options: ["Manchester United", "Chelsea", "Liverpool", "Arsenal"], correctAnswer: "Liverpool", difficulty: 1 },
  { id: 20, text: "¿Quién es el portero titular de la selección argentina (2022)?", options: ["Armani", "Dibu Martínez", "Rulli", "Musso"], correctAnswer: "Dibu Martínez", difficulty: 1 },
  { id: 21, text: "¿Qué país organizó el Mundial de 1970?", options: ["Brasil", "México", "Italia", "Chile"], correctAnswer: "México", difficulty: 1 },
  { id: 22, text: "¿Quién ganó la Eurocopa 2020 (jugada en 2021)?", options: ["Inglaterra", "Italia", "España", "Francia"], correctAnswer: "Italia", difficulty: 1 },
  { id: 23, text: "¿Cómo se llama el trofeo de la liga inglesa?", options: ["The Shield", "Premier League Trophy", "FA Cup", "Carabao Cup"], correctAnswer: "Premier League Trophy", difficulty: 1 },
  { id: 24, text: "¿Qué jugador es apodado 'La Pulga'?", options: ["Agüero", "Messi", "Dybala", "Di María"], correctAnswer: "Messi", difficulty: 1 },
  { id: 25, text: "¿Cuál es el estadio más grande de Sudamérica?", options: ["Maracaná", "Monumental (Arg)", "Monumental (Perú)", "Centenario"], correctAnswer: "Monumental (Arg)", difficulty: 1 },
  { id: 26, text: "¿En qué país nació Zlatan Ibrahimović?", options: ["Noruega", "Suecia", "Dinamarca", "Bosnia"], correctAnswer: "Suecia", difficulty: 1 },
  { id: 27, text: "¿Qué equipo ganó el triplete en 2023?", options: ["Real Madrid", "Manchester City", "Inter de Milán", "Bayern Múnich"], correctAnswer: "Manchester City", difficulty: 1 },
  { id: 28, text: "¿Quién es el máximo goleador de la selección de Brasil?", options: ["Pelé", "Ronaldo", "Neymar", "Romário"], correctAnswer: "Neymar", difficulty: 1 },
  { id: 29, text: "¿Cómo se llama el clásico de Argentina?", options: ["Boca vs River", "Racing vs Independiente", "San Lorenzo vs Huracán", "Rosario vs Newell's"], correctAnswer: "Boca vs River", difficulty: 1 },
  { id: 30, text: "¿Qué selección tiene más Copas del Mundo?", options: ["Alemania", "Italia", "Brasil", "Argentina"], correctAnswer: "Brasil", difficulty: 1 },
  { id: 31, text: "¿Quién marcó el gol de la 'Mano de Dios'?", options: ["Pelé", "Maradona", "Messi", "Kempes"], correctAnswer: "Maradona", difficulty: 1 },
  { id: 32, text: "¿En qué equipo juega Kylian Mbappé (2024)?", options: ["PSG", "Real Madrid", "Liverpool", "Arsenal"], correctAnswer: "Real Madrid", difficulty: 1 },
  { id: 33, text: "¿Qué selección ganó el primer Mundial de la historia?", options: ["Argentina", "Uruguay", "Brasil", "Francia"], correctAnswer: "Uruguay", difficulty: 1 },

  // Level 2: Intermediate
  { id: 34, text: "¿Quién ganó la Bota de Oro en el Mundial 2014?", options: ["Thomas Müller", "James Rodríguez", "Lionel Messi", "Neymar"], correctAnswer: "James Rodríguez", difficulty: 2 },
  { id: 35, text: "¿Qué equipo de la Premier League es conocido como 'The Gunners'?", options: ["Chelsea", "Tottenham", "Arsenal", "West Ham"], correctAnswer: "Arsenal", difficulty: 2 },
  { id: 36, text: "¿En qué año se fundó la FIFA?", options: ["1890", "1904", "1920", "1930"], correctAnswer: "1904", difficulty: 2 },
  { id: 37, text: "¿Quién es el jugador con más partidos en la historia de los Mundiales?", options: ["Lothar Matthäus", "Lionel Messi", "Miroslav Klose", "Paolo Maldini"], correctAnswer: "Lionel Messi", difficulty: 2 },
  { id: 38, text: "¿Qué equipo ganó la primera edición de la UEFA Nations League?", options: ["Francia", "Portugal", "España", "Holanda"], correctAnswer: "Portugal", difficulty: 2 },
  { id: 39, text: "¿Quién era el entrenador de España en el Mundial 2010?", options: ["Luis Aragonés", "Vicente del Bosque", "Pep Guardiola", "Luis Enrique"], correctAnswer: "Vicente del Bosque", difficulty: 2 },
  { id: 40, text: "¿En qué ciudad se encuentra el estadio San Siro?", options: ["Roma", "Milán", "Turín", "Nápoles"], correctAnswer: "Milán", difficulty: 2 },
  { id: 41, text: "¿Qué jugador marcó el gol de la victoria en la final del Mundial 2014?", options: ["Miroslav Klose", "Mario Götze", "Mesut Özil", "Toni Kroos"], correctAnswer: "Mario Götze", difficulty: 2 },
  { id: 42, text: "¿Cuál es el apodo de la selección de Holanda?", options: ["La Furia Roja", "La Naranja Mecánica", "Los Bleus", "La Albiceleste"], correctAnswer: "La Naranja Mecánica", difficulty: 2 },
  { id: 43, text: "¿Qué equipo ganó la Copa Libertadores 2018 en Madrid?", options: ["Boca Juniors", "River Plate", "Flamengo", "Palmeiras"], correctAnswer: "River Plate", difficulty: 2 },
  { id: 44, text: "¿Quién es el máximo goleador histórico de la Premier League?", options: ["Wayne Rooney", "Alan Shearer", "Harry Kane", "Sergio Agüero"], correctAnswer: "Alan Shearer", difficulty: 2 },
  { id: 45, text: "¿En qué país se jugó el Mundial de 1994?", options: ["Italia", "Estados Unidos", "Francia", "Japón"], correctAnswer: "Estados Unidos", difficulty: 2 },
  { id: 46, text: "¿Qué selección africana fue la primera en llegar a semifinales de un Mundial?", options: ["Camerún", "Senegal", "Ghana", "Marruecos"], correctAnswer: "Marruecos", difficulty: 2 },
  { id: 47, text: "¿Quién ganó el Balón de Oro en 2005?", options: ["Ronaldinho", "Zidane", "Kaká", "Cannavaro"], correctAnswer: "Ronaldinho", difficulty: 2 },
  { id: 48, text: "¿Cómo se llama el estadio del Bayern Múnich?", options: ["Signal Iduna Park", "Allianz Arena", "Olympiastadion", "Veltins-Arena"], correctAnswer: "Allianz Arena", difficulty: 2 },
  { id: 49, text: "¿Qué jugador es conocido como 'El Fenómeno'?", options: ["Cristiano Ronaldo", "Ronaldinho", "Ronaldo Nazário", "Romário"], correctAnswer: "Ronaldo Nazário", difficulty: 2 },
  { id: 50, text: "¿En qué año ganó Inglaterra su único Mundial?", options: ["1958", "1962", "1966", "1970"], correctAnswer: "1966", difficulty: 2 },
  { id: 51, text: "¿Quién ostenta el récord de más goles en un solo año natural?", options: ["Cristiano Ronaldo", "Lionel Messi", "Gerd Müller", "Pelé"], correctAnswer: "Lionel Messi", difficulty: 2 },
  { id: 52, text: "¿Qué equipo de Italia es apodado 'La Vecchia Signora'?", options: ["AC Milan", "Inter de Milán", "Juventus", "AS Roma"], correctAnswer: "Juventus", difficulty: 2 },
  { id: 53, text: "¿Quién marcó el gol de 'La Mano de Dios' y el 'Gol del Siglo' en el mismo partido?", options: ["Pelé", "Maradona", "Zidane", "Cruyff"], correctAnswer: "Maradona", difficulty: 2 },
  { id: 54, text: "¿Qué selección ganó la Copa América 2021?", options: ["Brasil", "Argentina", "Colombia", "Chile"], correctAnswer: "Argentina", difficulty: 2 },
  { id: 55, text: "¿En qué equipo jugaba David Beckham cuando se retiró?", options: ["LA Galaxy", "AC Milan", "PSG", "Real Madrid"], correctAnswer: "PSG", difficulty: 2 },
  { id: 56, text: "¿Quién es el máximo goleador histórico de la Champions League?", options: ["Lionel Messi", "Cristiano Ronaldo", "Robert Lewandowski", "Karim Benzema"], correctAnswer: "Cristiano Ronaldo", difficulty: 2 },
  { id: 57, text: "¿Qué selección ganó el Mundial de 1998?", options: ["Brasil", "Francia", "Croacia", "Italia"], correctAnswer: "Francia", difficulty: 2 },
  { id: 58, text: "¿Cómo se llama el estadio del Borussia Dortmund?", options: ["Allianz Arena", "Signal Iduna Park", "Veltins-Arena", "Mercedes-Benz Arena"], correctAnswer: "Signal Iduna Park", difficulty: 2 },
  { id: 59, text: "¿Qué jugador ganó 3 Mundiales?", options: ["Maradona", "Pelé", "Cafú", "Ronaldo"], correctAnswer: "Pelé", difficulty: 2 },
  { id: 60, text: "¿En qué ciudad se jugó la final de la Champions 2023?", options: ["París", "Estambul", "Londres", "Madrid"], correctAnswer: "Estambul", difficulty: 2 },
  { id: 61, text: "¿Quién es el máximo goleador de la selección de Francia?", options: ["Thierry Henry", "Olivier Giroud", "Kylian Mbappé", "Zinedine Zidane"], correctAnswer: "Olivier Giroud", difficulty: 2 },
  { id: 62, text: "¿Qué equipo ganó la Europa League 2023?", options: ["Roma", "Sevilla", "Juventus", "Bayer Leverkusen"], correctAnswer: "Sevilla", difficulty: 2 },
  { id: 63, text: "¿Quién fue el Balón de Oro en 2018?", options: ["Cristiano Ronaldo", "Luka Modrić", "Antoine Griezmann", "Lionel Messi"], correctAnswer: "Luka Modrić", difficulty: 2 },
  { id: 64, text: "¿En qué país nació Erling Haaland?", options: ["Noruega", "Inglaterra", "Alemania", "Dinamarca"], correctAnswer: "Inglaterra", difficulty: 2 },
  { id: 65, text: "¿Qué selección ganó la Copa Oro 2023?", options: ["Estados Unidos", "México", "Panamá", "Canadá"], correctAnswer: "México", difficulty: 2 },
  { id: 66, text: "¿Quién es el entrenador del Manchester City (2024)?", options: ["Jürgen Klopp", "Pep Guardiola", "Carlo Ancelotti", "Mikel Arteta"], correctAnswer: "Pep Guardiola", difficulty: 2 },

  // Level 3: Advanced
  { id: 67, text: "¿Quién fue el máximo goleador del Mundial de México 1986?", options: ["Maradona", "Gary Lineker", "Emilio Butragueño", "Careca"], correctAnswer: "Gary Lineker", difficulty: 3 },
  { id: 68, text: "¿Qué equipo ganó la Champions League en 1999 con una remontada épica?", options: ["Bayern Múnich", "Manchester United", "Real Madrid", "Juventus"], correctAnswer: "Manchester United", difficulty: 3 },
  { id: 69, text: "¿En qué año se introdujo el VAR en un Mundial por primera vez?", options: ["2014", "2018", "2022", "2010"], correctAnswer: "2018", difficulty: 3 },
  { id: 70, text: "¿Quién es el único portero en ganar el Balón de Oro?", options: ["Gianluigi Buffon", "Lev Yashin", "Manuel Neuer", "Iker Casillas"], correctAnswer: "Lev Yashin", difficulty: 3 },
  { id: 71, text: "¿Qué selección ganó la Eurocopa de 1992 sin haberse clasificado inicialmente?", options: ["Dinamarca", "Grecia", "Yugoslavia", "Suecia"], correctAnswer: "Dinamarca", difficulty: 3 },
  { id: 72, text: "¿Quién marcó el gol de oro en la final de la Eurocopa 2000?", options: ["Zinedine Zidane", "David Trezeguet", "Thierry Henry", "Sylvain Wiltord"], correctAnswer: "David Trezeguet", difficulty: 3 },
  { id: 73, text: "¿En qué equipo jugaba George Weah cuando ganó el Balón de Oro?", options: ["PSG", "AC Milan", "Mónaco", "Chelsea"], correctAnswer: "AC Milan", difficulty: 3 },
  { id: 74, text: "¿Qué país organizó el primer Mundial femenino en 1991?", options: ["Estados Unidos", "China", "Suecia", "Noruega"], correctAnswer: "China", difficulty: 3 },
  { id: 75, text: "¿Quién es el máximo goleador histórico de la selección de Italia?", options: ["Alessandro Del Piero", "Luigi Riva", "Roberto Baggio", "Giuseppe Meazza"], correctAnswer: "Luigi Riva", difficulty: 3 },
  { id: 76, text: "¿Qué equipo ganó la Copa Intercontinental en 1960 (la primera edición)?", options: ["Peñarol", "Real Madrid", "Benfica", "Santos"], correctAnswer: "Real Madrid", difficulty: 3 },
  { id: 77, text: "¿Quién fue el capitán de Brasil en el Mundial de 1994?", options: ["Romário", "Dunga", "Rai", "Bebeto"], correctAnswer: "Dunga", difficulty: 3 },
  { id: 78, text: "¿En qué año ganó el Steaua de Bucarest la Copa de Europa?", options: ["1984", "1986", "1988", "1990"], correctAnswer: "1986", difficulty: 3 },
  { id: 79, text: "¿Quién es el jugador con más títulos oficiales en la historia del fútbol?", options: ["Dani Alves", "Lionel Messi", "Cristiano Ronaldo", "Andrés Iniesta"], correctAnswer: "Lionel Messi", difficulty: 3 },
  { id: 80, text: "¿Qué selección ganó la Copa Confederaciones 2005?", options: ["Brasil", "Argentina", "Alemania", "México"], correctAnswer: "Brasil", difficulty: 3 },
  { id: 81, text: "¿Quién era el entrenador del 'Dream Team' del FC Barcelona?", options: ["Pep Guardiola", "Johan Cruyff", "Bobby Robson", "Louis van Gaal"], correctAnswer: "Johan Cruyff", difficulty: 3 },
  { id: 82, text: "¿En qué estadio se jugó el 'Maracanazo' en 1950?", options: ["Centenario", "Maracaná", "Pacaembú", "San Januário"], correctAnswer: "Maracaná", difficulty: 3 },
  { id: 83, text: "¿Quién ganó el Balón de Oro en 1995 (primer no europeo)?", options: ["George Weah", "Ronaldo", "Romário", "Batistuta"], correctAnswer: "George Weah", difficulty: 3 },
  { id: 84, text: "¿Qué selección ganó el Mundial de 1954 (el Milagro de Berna)?", options: ["Hungría", "Alemania Federal", "Austria", "Uruguay"], correctAnswer: "Alemania Federal", difficulty: 3 },
  { id: 85, text: "¿Quién es el máximo goleador histórico de la selección de Alemania?", options: ["Gerd Müller", "Miroslav Klose", "Lukas Podolski", "Jürgen Klinsmann"], correctAnswer: "Miroslav Klose", difficulty: 3 },
  { id: 86, text: "¿En qué equipo jugaba Johan Cruyff cuando ganó su primer Balón de Oro?", options: ["FC Barcelona", "Ajax", "Feyenoord", "Los Angeles Aztecs"], correctAnswer: "Ajax", difficulty: 3 },
  { id: 87, text: "¿Qué equipo ganó la Copa Libertadores en 1991 (único chileno)?", options: ["Universidad de Chile", "Colo-Colo", "Universidad Católica", "Cobreloa"], correctAnswer: "Colo-Colo", difficulty: 3 },
  { id: 88, text: "¿Quién marcó el gol de la victoria para Alemania en la final de 1990?", options: ["Lothar Matthäus", "Andreas Brehme", "Jürgen Klinsmann", "Rudi Völler"], correctAnswer: "Andreas Brehme", difficulty: 3 },
  { id: 89, text: "¿Qué selección ganó la Eurocopa de 2004?", options: ["Portugal", "Grecia", "República Checa", "Francia"], correctAnswer: "Grecia", difficulty: 3 },
  { id: 90, text: "¿Quién es el máximo goleador histórico de la selección de España?", options: ["Raúl González", "David Villa", "Fernando Torres", "Álvaro Morata"], correctAnswer: "David Villa", difficulty: 3 },
  { id: 91, text: "¿En qué año se fundó la Premier League?", options: ["1988", "1990", "1992", "1994"], correctAnswer: "1992", difficulty: 3 },
  { id: 92, text: "¿Quién ganó el Balón de Oro en 2004?", options: ["Thierry Henry", "Andriy Shevchenko", "Ronaldinho", "Deco"], correctAnswer: "Andriy Shevchenko", difficulty: 3 },
  { id: 93, text: "¿Qué equipo de Inglaterra ha ganado más ligas históricamente?", options: ["Liverpool", "Manchester United", "Arsenal", "Everton"], correctAnswer: "Manchester United", difficulty: 3 },
  { id: 94, text: "¿Quién fue el máximo goleador del Mundial de 1970?", options: ["Pelé", "Gerd Müller", "Jairzinho", "Teófilo Cubillas"], correctAnswer: "Gerd Müller", difficulty: 3 },
  { id: 95, text: "¿En qué equipo jugaba Diego Maradona cuando ganó el Mundial 1986?", options: ["Boca Juniors", "FC Barcelona", "Nápoles", "Sevilla"], correctAnswer: "Nápoles", difficulty: 3 },
  { id: 96, text: "¿Qué selección ganó la Copa América de 2001?", options: ["Brasil", "Colombia", "México", "Honduras"], correctAnswer: "Colombia", difficulty: 3 },
  { id: 97, text: "¿Quién es el máximo goleador histórico de la selección de Francia?", options: ["Thierry Henry", "Olivier Giroud", "Kylian Mbappé", "Zinedine Zidane"], correctAnswer: "Olivier Giroud", difficulty: 3 },
  { id: 98, text: "¿Qué equipo ganó la Champions League en 2004?", options: ["Mónaco", "Oporto", "Chelsea", "Real Madrid"], correctAnswer: "Oporto", difficulty: 3 },
  { id: 99, text: "¿Quién fue el entrenador de Argentina en el Mundial 1986?", options: ["César Luis Menotti", "Carlos Bilardo", "Alfio Basile", "Daniel Passarella"], correctAnswer: "Carlos Bilardo", difficulty: 3 },
  { id: 100, text: "¿En qué año se jugó el primer Mundial femenino?", options: ["1988", "1991", "1995", "1999"], correctAnswer: "1991", difficulty: 3 },
  { id: 101, text: "¿Qué estadio es el de la imagen?", options: ["Wembley", "Maracaná", "Camp Nou", "Old Trafford"], correctAnswer: "Maracaná", difficulty: 2, image: "https://images.unsplash.com/photo-1599423300746-b62533397364?auto=format&fit=crop&q=80&w=800" },
  { id: 102, text: "¿A qué equipo pertenece este escudo (simulado)?", options: ["Real Madrid", "Juventus", "Liverpool", "Bayern"], correctAnswer: "Juventus", difficulty: 1, image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&q=80&w=800" },
  { id: 103, text: "¿Quién es el jugador de la imagen?", options: ["Lionel Messi", "Cristiano Ronaldo", "Neymar Jr", "Kylian Mbappé"], correctAnswer: "Lionel Messi", difficulty: 1, image: "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&q=80&w=800" },
  { id: 104, text: "¿En qué ciudad se encuentra este famoso estadio?", options: ["Londres", "Madrid", "Múnich", "Dortmund"], correctAnswer: "Londres", difficulty: 2, image: "https://images.unsplash.com/photo-1529900748604-07564a03e7a6?auto=format&fit=crop&q=80&w=800" },
  { id: 105, text: "¿Qué trofeo es el que se muestra?", options: ["Copa del Mundo", "Champions League", "Copa América", "Eurocopa"], correctAnswer: "Champions League", difficulty: 1, image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=800" },
  { id: 106, text: "¿Qué selección utiliza este uniforme?", options: ["Brasil", "Colombia", "Suecia", "Australia"], correctAnswer: "Brasil", difficulty: 1, image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800" },
  
  // Colombian Football Questions
  // Level 1
  { id: 107, text: "¿Qué equipo es conocido como 'El Rey de Copas' en Colombia?", options: ["Millonarios", "Atlético Nacional", "América de Cali", "Santa Fe"], correctAnswer: "Atlético Nacional", difficulty: 1 },
  { id: 108, text: "¿Cuál es el estadio principal de la Selección Colombia en Barranquilla?", options: ["El Campín", "Atanasio Girardot", "Metropolitano", "Pascual Guerrero"], correctAnswer: "Metropolitano", difficulty: 1 },
  { id: 109, text: "¿Quién es el máximo goleador histórico de la Selección Colombia?", options: ["James Rodríguez", "Radamel Falcao", "Arnold Iguarán", "Faustino Asprilla"], correctAnswer: "Radamel Falcao", difficulty: 1 },
  { id: 110, text: "¿Qué equipo ganó la primera estrella del fútbol colombiano en 1948?", options: ["Millonarios", "Santa Fe", "Atlético Nacional", "Deportivo Cali"], correctAnswer: "Santa Fe", difficulty: 1 },
  { id: 111, text: "¿Cómo le dicen popularmente a la Selección Colombia?", options: ["La Roja", "La Albiceleste", "La Tricolor", "La Canarinha"], correctAnswer: "La Tricolor", difficulty: 1 },
  
  // Level 2
  { id: 112, text: "¿Qué equipo colombiano ganó la Copa Libertadores en 1989?", options: ["América de Cali", "Atlético Nacional", "Millonarios", "Junior"], correctAnswer: "Atlético Nacional", difficulty: 2 },
  { id: 113, text: "¿En qué equipo jugaba Carlos 'El Pibe' Valderrama en Barranquilla?", options: ["Junior", "Unión Magdalena", "Independiente Medellín", "Millonarios"], correctAnswer: "Junior", difficulty: 2 },
  { id: 114, text: "¿Quién era el arquero de Colombia en el Mundial de Italia 90?", options: ["Óscar Córdoba", "Faryd Mondragón", "René Higuita", "Miguel Calero"], correctAnswer: "René Higuita", difficulty: 2 },
  { id: 115, text: "¿Qué equipo es conocido como 'El Embajador' en Bogotá?", options: ["Santa Fe", "Millonarios", "La Equidad", "Bogotá FC"], correctAnswer: "Millonarios", difficulty: 2 },
  { id: 116, text: "¿Quién marcó el gol del empate contra Alemania en el Mundial de 1990?", options: ["Carlos Valderrama", "Freddy Rincón", "Bernardo Redín", "Adolfo Valencia"], correctAnswer: "Freddy Rincón", difficulty: 2 },
  
  // Level 3
  { id: 117, text: "¿Quién es el máximo goleador histórico de la liga colombiana?", options: ["Iván René Valenciano", "Sergio Galván Rey", "Hugo Horacio Lóndero", "Antony de Ávila"], correctAnswer: "Sergio Galván Rey", difficulty: 3 },
  { id: 118, text: "¿Qué equipo ganó la Copa Libertadores en 2004 venciendo a Boca Juniors?", options: ["Atlético Nacional", "Once Caldas", "América de Cali", "Deportivo Cali"], correctAnswer: "Once Caldas", difficulty: 3 },
  { id: 119, text: "¿En qué año se fundó la DIMAYOR?", options: ["1938", "1945", "1948", "1952"], correctAnswer: "1948", difficulty: 3 },
  { id: 120, text: "¿Quién fue el primer colombiano en ganar la Champions League?", options: ["James Rodríguez", "Iván Ramiro Córdoba", "Juan Guillermo Cuadrado", "Luis Díaz"], correctAnswer: "Iván Ramiro Córdoba", difficulty: 3 },
  { id: 121, text: "¿Qué equipo colombiano tiene más títulos de liga actualmente (2024)?", options: ["Millonarios", "América de Cali", "Atlético Nacional", "Santa Fe"], correctAnswer: "Atlético Nacional", difficulty: 3 },

  // Level 1: More Basic Questions
  { id: 122, text: "¿Cómo se llama el trofeo que se entrega al campeón del mundo?", options: ["Copa FIFA", "Copa Jules Rimet", "Copa del Mundo", "Copa Oro"], correctAnswer: "Copa del Mundo", difficulty: 1 },
  { id: 123, text: "¿Qué selección es conocida como 'La Azzurra'?", options: ["Francia", "Italia", "Grecia", "Uruguay"], correctAnswer: "Italia", difficulty: 1 },
  { id: 124, text: "¿En qué país juega el Inter de Miami?", options: ["España", "Estados Unidos", "Argentina", "México"], correctAnswer: "Estados Unidos", difficulty: 1 },
  { id: 125, text: "¿Quién es el máximo goleador de la selección de Portugal?", options: ["Eusébio", "Luís Figo", "Cristiano Ronaldo", "Pauleta"], correctAnswer: "Cristiano Ronaldo", difficulty: 1 },
  { id: 126, text: "¿Qué equipo tiene como estadio el 'Old Trafford'?", options: ["Manchester City", "Manchester United", "Liverpool", "Chelsea"], correctAnswer: "Manchester United", difficulty: 1 },
  { id: 127, text: "¿Cuál es el color de la camiseta de la selección de Brasil?", options: ["Azul", "Blanco", "Amarillo", "Verde"], correctAnswer: "Amarillo", difficulty: 1 },
  { id: 128, text: "¿Cómo se llama el clásico entre Real Madrid y Barcelona?", options: ["El Derbi", "El Gran Partido", "El Clásico", "La Final"], correctAnswer: "El Clásico", difficulty: 1 },
  { id: 129, text: "¿Quién ganó el Mundial de 2018?", options: ["Croacia", "Bélgica", "Francia", "Inglaterra"], correctAnswer: "Francia", difficulty: 1 },
  { id: 130, text: "¿Qué jugador es apodado 'El Pistolero'?", options: ["Cavani", "Luis Suárez", "Forlán", "Darwin Núñez"], correctAnswer: "Luis Suárez", difficulty: 1 },
  { id: 131, text: "¿En qué continente se jugó el Mundial 2010?", options: ["Europa", "Asia", "África", "América"], correctAnswer: "África", difficulty: 1 },

  // Level 2: More Intermediate Questions
  { id: 132, text: "¿Qué equipo ganó la Champions League en 2012 por primera vez?", options: ["Manchester City", "Chelsea", "PSG", "Tottenham"], correctAnswer: "Chelsea", difficulty: 2 },
  { id: 133, text: "¿Quién fue el entrenador de Argentina en el Mundial 2022?", options: ["Sampaoli", "Scaloni", "Pekerman", "Sabella"], correctAnswer: "Scaloni", difficulty: 2 },
  { id: 134, text: "¿Qué jugador marcó el gol de la victoria para España en la final de 2010?", options: ["Xavi", "Iniesta", "Villa", "Torres"], correctAnswer: "Iniesta", difficulty: 2 },
  { id: 135, text: "¿En qué equipo jugaba Ronaldinho antes de ir al Barcelona?", options: ["PSG", "Milan", "Gremio", "Flamengo"], correctAnswer: "PSG", difficulty: 2 },
  { id: 136, text: "¿Qué selección africana eliminó a España en el Mundial 2022?", options: ["Egipto", "Marruecos", "Senegal", "Ghana"], correctAnswer: "Marruecos", difficulty: 2 },
  { id: 137, text: "¿Quién es el máximo goleador histórico del Real Madrid?", options: ["Raúl", "Cristiano Ronaldo", "Benzema", "Di Stéfano"], correctAnswer: "Cristiano Ronaldo", difficulty: 2 },
  { id: 138, text: "¿Qué equipo de la Premier League juega en el Etihad Stadium?", options: ["Arsenal", "Manchester City", "Leicester", "Everton"], correctAnswer: "Manchester City", difficulty: 2 },
  { id: 139, text: "¿En qué año se jugó el Mundial de Corea-Japón?", options: ["1998", "2002", "2006", "2010"], correctAnswer: "2002", difficulty: 2 },
  { id: 140, text: "¿Qué jugador ganó el Balón de Oro en 2022?", options: ["Messi", "Benzema", "Lewandowski", "Mané"], correctAnswer: "Benzema", difficulty: 2 },
  { id: 141, text: "¿Cómo se llama el estadio del Atlético de Madrid actual?", options: ["Vicente Calderón", "Metropolitano", "La Peineta", "Vallecas"], correctAnswer: "Metropolitano", difficulty: 2 },

  // Level 3: More Advanced Questions
  { id: 142, text: "¿Quién fue el máximo goleador del Mundial de Francia 1998?", options: ["Ronaldo", "Davor Šuker", "Batistuta", "Vieri"], correctAnswer: "Davor Šuker", difficulty: 3 },
  { id: 143, text: "¿Qué equipo ganó la Champions League en 1995?", options: ["Milan", "Ajax", "Juventus", "Real Madrid"], correctAnswer: "Ajax", difficulty: 3 },
  { id: 144, text: "¿En qué año ganó Dinamarca la Eurocopa?", options: ["1988", "1992", "1996", "2000"], correctAnswer: "1992", difficulty: 3 },
  { id: 145, text: "¿Quién es el jugador con más partidos en la selección de Alemania?", options: ["Müller", "Klose", "Lothar Matthäus", "Lahm"], correctAnswer: "Lothar Matthäus", difficulty: 3 },
  { id: 146, text: "¿Qué selección ganó la Copa América de 1997?", options: ["Brasil", "Bolivia", "Argentina", "Perú"], correctAnswer: "Brasil", difficulty: 3 },
  { id: 147, text: "¿Quién marcó el gol de la victoria para Grecia en la final de la Euro 2004?", options: ["Charisteas", "Zagorakis", "Basinas", "Dellas"], correctAnswer: "Charisteas", difficulty: 3 },
  { id: 148, text: "¿En qué equipo jugaba Zinedine Zidane antes de ir a la Juventus?", options: ["Marsella", "Burdeos", "Cannes", "Mónaco"], correctAnswer: "Burdeos", difficulty: 3 },
  { id: 149, text: "¿Qué país organizó el Mundial de 1962?", options: ["Brasil", "Chile", "Argentina", "Uruguay"], correctAnswer: "Chile", difficulty: 3 },
  { id: 150, text: "¿Quién fue el Balón de Oro en 1999?", options: ["Beckham", "Rivaldo", "Shevchenko", "Zidane"], correctAnswer: "Rivaldo", difficulty: 3 },

  // More Colombian Questions
  { id: 151, text: "¿Quién es el arquero con más partidos en la Selección Colombia?", options: ["Óscar Córdoba", "David Ospina", "René Higuita", "Faryd Mondragón"], correctAnswer: "David Ospina", difficulty: 1 },
  { id: 152, text: "¿Qué equipo colombiano es conocido como 'El Poderoso'?", options: ["Atlético Nacional", "Independiente Medellín", "Junior", "Deportivo Cali"], correctAnswer: "Independiente Medellín", difficulty: 1 },
  { id: 153, text: "¿En qué ciudad juega el equipo Once Caldas?", options: ["Pereira", "Manizales", "Armenia", "Ibagué"], correctAnswer: "Manizales", difficulty: 1 },
  { id: 154, text: "¿Quién marcó el gol de Colombia contra Brasil en el Mundial 2014?", options: ["James Rodríguez", "Juan Cuadrado", "Jackson Martínez", "Teófilo Gutiérrez"], correctAnswer: "James Rodríguez", difficulty: 1 },
  { id: 155, text: "¿Qué equipo tiene el apodo de 'Los Azucareros'?", options: ["América de Cali", "Deportivo Cali", "Cortuluá", "Deportivo Pasto"], correctAnswer: "Deportivo Cali", difficulty: 1 },
  { id: 156, text: "¿Quién fue el técnico de Colombia en el Mundial 2014?", options: ["Hernán Darío Gómez", "José Pékerman", "Leonel Álvarez", "Reinaldo Rueda"], correctAnswer: "José Pékerman", difficulty: 2 },
  { id: 157, text: "¿Qué jugador colombiano es apodado 'El Tigre'?", options: ["Luis Díaz", "Radamel Falcao", "Duván Zapata", "Rafael Santos Borré"], correctAnswer: "Radamel Falcao", difficulty: 1 },
  { id: 158, text: "¿En qué año ganó Colombia su única Copa América?", options: ["1999", "2001", "2004", "2007"], correctAnswer: "2001", difficulty: 2 },
  { id: 159, text: "¿Qué equipo colombiano llegó a 3 finales consecutivas de Libertadores en los 80?", options: ["Atlético Nacional", "América de Cali", "Millonarios", "Deportivo Cali"], correctAnswer: "América de Cali", difficulty: 3 },
  { id: 160, text: "¿Quién es el máximo goleador histórico de Millonarios?", options: ["Alfredo Di Stéfano", "Fernando Uribe", "Alejandro Brand", "Jaime Morón"], correctAnswer: "Alfredo Di Stéfano", difficulty: 3 },
  { id: 161, text: "¿Qué jugador tiene el récord de más goles en un solo Mundial?", options: ["Pelé", "Just Fontaine", "Müller", "Ronaldo"], correctAnswer: "Just Fontaine", difficulty: 3 },
  { id: 162, text: "¿En qué equipo jugaba Lionel Messi cuando ganó su primer Balón de Oro?", options: ["PSG", "Barcelona", "Argentina", "Newell's"], correctAnswer: "Barcelona", difficulty: 1 },
  { id: 163, text: "¿Qué selección ha ganado más Copas América?", options: ["Brasil", "Argentina", "Uruguay", "Chile"], correctAnswer: "Argentina", difficulty: 2 },
  { id: 164, text: "¿Quién es el máximo goleador histórico de la Selección de Inglaterra?", options: ["Wayne Rooney", "Harry Kane", "Bobby Charlton", "Gary Lineker"], correctAnswer: "Harry Kane", difficulty: 2 },
  { id: 165, text: "¿En qué año se fundó la FIFA?", options: ["1900", "1904", "1910", "1920"], correctAnswer: "1904", difficulty: 3 },
  { id: 166, text: "¿Qué equipo de la Bundesliga es conocido como 'Los Aspirinas'?", options: ["Bayern Munich", "Borussia Dortmund", "Bayer Leverkusen", "RB Leipzig"], correctAnswer: "Bayer Leverkusen", difficulty: 2 },
  { id: 167, text: "¿Quién fue el portero titular de España en el Mundial 2010?", options: ["Víctor Valdés", "Pepe Reina", "Iker Casillas", "De Gea"], correctAnswer: "Iker Casillas", difficulty: 1 },
  { id: 168, text: "¿Qué jugador es apodado 'La Joya'?", options: ["Lautaro Martínez", "Paulo Dybala", "Ángel Di María", "Julián Álvarez"], correctAnswer: "Paulo Dybala", difficulty: 1 },
  { id: 169, text: "¿En qué país se encuentra el estadio Maracaná?", options: ["Argentina", "Uruguay", "Brasil", "Colombia"], correctAnswer: "Brasil", difficulty: 1 },
  { id: 170, text: "¿Qué equipo ganó la primera edición de la Copa Libertadores?", options: ["Santos", "Peñarol", "Independiente", "Boca Juniors"], correctAnswer: "Peñarol", difficulty: 3 },
  { id: 171, text: "¿Quién es el máximo goleador de la Selección de Chile?", options: ["Iván Zamorano", "Marcelo Salas", "Alexis Sánchez", "Eduardo Vargas"], correctAnswer: "Alexis Sánchez", difficulty: 2 },
  { id: 172, text: "¿Qué selección ganó la Eurocopa 2016?", options: ["Francia", "Alemania", "Portugal", "España"], correctAnswer: "Portugal", difficulty: 1 },
  { id: 173, text: "¿En qué equipo jugaba Erling Haaland antes del Manchester City?", options: ["Molde", "Salzburg", "Borussia Dortmund", "Leipzig"], correctAnswer: "Borussia Dortmund", difficulty: 1 },
  { id: 174, text: "¿Quién es el único jugador en ganar 3 Copas del Mundo?", options: ["Maradona", "Pelé", "Zidane", "Ronaldo"], correctAnswer: "Pelé", difficulty: 1 },
  { id: 175, text: "¿Qué equipo colombiano es conocido como 'El Blanco Blanco'?", options: ["Millonarios", "Santa Fe", "Once Caldas", "Real Cartagena"], correctAnswer: "Once Caldas", difficulty: 1 },
  { id: 176, text: "¿Quién marcó el gol del 5-0 de Colombia contra Argentina en 1993 (último gol)?", options: ["Faustino Asprilla", "Freddy Rincón", "Adolfo Valencia", "Anthony de Ávila"], correctAnswer: "Adolfo Valencia", difficulty: 3 },
  { id: 177, text: "¿En qué año debutó James Rodríguez en la Selección Colombia de mayores?", options: ["2010", "2011", "2012", "2013"], correctAnswer: "2011", difficulty: 3 },
  { id: 178, text: "¿Qué equipo colombiano juega en el estadio Manuel Murillo Toro?", options: ["Deportivo Pasto", "Deportes Tolima", "Atlético Huila", "Deportivo Cali"], correctAnswer: "Deportes Tolima", difficulty: 2 },
  { id: 179, text: "¿Quién es el máximo goleador histórico del Junior de Barranquilla?", options: ["Carlos Bacca", "Iván René Valenciano", "Teófilo Gutiérrez", "Víctor Ephanor"], correctAnswer: "Iván René Valenciano", difficulty: 3 },
  { id: 180, text: "¿Qué selección ganó la Copa Oro 2023?", options: ["Estados Unidos", "México", "Panamá", "Canadá"], correctAnswer: "México", difficulty: 2 },
];
